### ISSUE TITLE
Only plays a limited count of items

### ISSUE THREAD

**Issue by thoasty-dev** [phiamo/capacitor-plugin-playlist#12]
Hey there, I got the issue on iOS (emulator and real device) that only a limited count of items is played and then the player jumps back to start (first item). For example if I add 18 items, only 10 are played. This isnt consistent however, sometimes I add 5 items and only 3 are played. I couldnt find any pattern yet. Did anybody have a similar issue?

Best regards

Edit: This only happens when I call skipForward. If I "let it play through", it works as expected.

**Comment by thoasty-dev** [comment]
Update:

If I comment out the code of AVBidirectionalQueuePlayer.swift like this everything seems to work fine so far:

```
open override func advanceToNextItem() {
        super.advanceToNextItem();
        // if currentIndex() == nil || currentIndex()! < items().count - 1{
        //    super.advanceToNextItem();
        // } else {
        //    setCurrentIndex(0)
        // }
    }
```

**Comment by PavelShvets-dev** [comment]
Got the same issue. The fix should be:
currentIndex < items.count()

Otherwise we will always lost the last item and start from the beginning (index 0)

**Comment by thoasty-dev** [comment]
Imo, it seems to be a problem of the check ``currentIndex() == nil``, because as I said, sometimes there would be multiple more tracks after the current track.

**Comment by thoasty-dev** [comment]
Info: this should be fixed by https://github.com/phiamo/capacitor-plugin-playlist/commit/ad924ea88ef71badc9c12e1c50bf96ccd3804868

**Comment by phiamo** [comment]
arg sorry forgot recently to update the issue, thanks guys for pointing me to the right direction
