### ISSUE TITLE
Changing rate

### ISSUE THREAD

**Issue by PavelShvets-dev** [phiamo/capacitor-plugin-playlist#16]
I got (not always) the following issue: when my phone connected to Bluetooth system some tracks begin to change rate (playing faster or slower) themselves. Does anybody got the same and maybe know the reason?

**Comment by thoasty-dev** [comment]
Hey there

1) What platforms (iOS / Android) are effected?

2) What is the format / bitrate / quality of the audio you are playing? Have you tried to reduce the quality and does that have any effect?

Best regards

**Comment by PavelShvets-dev** [comment]
Hi,
Thanks for your reply!

1. Both: iOS and Android, but more cases with iOS 
2. MP3, 320, high quality. I haven't try to reduce quality.

[here is the link for example track](https://drive.google.com/file/d/1xvZXrqiVnePvzEq4Itgl7uec-e34tPUm/view?usp=drivesdk)

Do you know the possible reason of that issue?

**Comment by phiamo** [comment]
huh, i never had such an issue, i am playing mainly high quality mp3 and hls streams

**Comment by PavelShvets-dev** [comment]
@phiamo maybe it will help to understand reason: current problem appears just with some bluetooth systems. In my case: Tascam CD-200BT. But if we use simple receivers like Logitech Bluetooth Receiver - there is not problem with playback.

**Comment by PavelShvets-dev** [comment]
@phiamo hi! Let's close current issue, I'm not sure 100%, but I found just one reason - according BT spec, if client loses some server packets Bt will try to smooth that hole and we'll hear pitching up or down.
