### ISSUE TITLE
Listening for status changes

### ISSUE THREAD

**Issue by timstoute** [phiamo/capacitor-plugin-playlist#19]
Looking for advice on best practices with this plugin to detect status changes. I've created the following Angular code to detect and react to changes in the player status...any advice. Is there a better / more appropriate way to this? I'm using rxjs pairwise to compare status values emitted from the observable subscription, and then when a value exists and changes, action can be taken.

`
// listening for status changes

    ngAfterViewInit() {

      this.status$.pipe(
        pairwise(),
        map(values => ({
          prev: values[0],
          current: values[1]
        })))

      .subscribe((pairwise: any) => {

       // create a listener to determine when currentTrack has changed

        this.currentTrackId = pairwise.current.trackId;
        this.nextTrackId = pairwise.prev.trackId;

        if (this.nextTrackId != this.currentTrackId) { // if there is a current track, then set it to played status
          console.log("setting track played status to 'played' = ", this.currentTrackId)
          this.database.setListenProfileTrackStatus(this.user.uid, this.user.selectedListenProfile, this.currentTrackId, "played")
        } else {
          console.log("track id did not change with last emit")
        }
      }  }
`

**Comment by phiamo** [comment]
I am doing it this way in angular
```
        Playlist.addListener('status', (data: PlaylistStatusChangeCallbackArg) => {
            return this.ngZone.run(async () => {
                if (data.action === 'status') {
                    const status: any = data.status;
                    log.debug(status);
                    let playlistItem: PlaylistItem | undefined;
                    try {
                        playlistItem = this.playlistService.createItemByIdent(status.trackId);
                    } catch (error) {
                    }
                    switch (status.msgType) {
                        case RmxAudioStatusMessage.RMXSTATUS_ERROR: // 5
                            if (status.value && status.value.message && /401/.test(status.value.message)) {
                                const wasPlaying = this.currentState == PLAYER_STATE.PLAYING;
                                await this.recreatePlaylist();
                                if (wasPlaying) {
                                    await this.play(null, null, false);
                                }
                            }
                            break; 
```

**Comment by timstoute** [comment]
thanks, I've adopted the switch / case structure now
