### ISSUE TITLE
Does this work to play a playlist in the background?

### ISSUE THREAD

**Issue by rwwagner90** [phiamo/capacitor-plugin-playlist#2]
It's unclear from the README if this works for playing a list of tracks in the background or not.

**Comment by phiamo** [comment]
Hi sorry for the late reply. 
Yes
Thats exactly the intention to have playlist also be able to switch to the next track in the background which is afaik not possible from javascript conext

**Comment by rwwagner90** [comment]
@phiamo is there a way to show next/previous and play/pause and such on the lock screen? I got a playlist playing in the background, but no controls show up.

**Comment by phiamo** [comment]
mhh, if you have the native capacitor parts running, this should show up,
are we talking about android or ios ?

Am Di., 9. Feb. 2021 um 18:52 Uhr schrieb Robert Wagner <
notifications@github.com>:

**Comment by rwwagner90** [comment]
@phiamo just iOS so far

**Comment by phiamo** [comment]
Honestly, i dont remember the steps, exactly, and dont have time this week to look into it detailled,

but e.g. on the  simulator they never show up, this seems just to work on real devices.

di you check on a real device already?
