### ISSUE TITLE
Argument of type 'AudioTrackOptions' is not assignable to parameter of type 'PlaylistItemOptions'

### ISSUE THREAD

**Issue by timstoute** [phiamo/capacitor-plugin-playlist#20]
Using this plugin with Ionic (see Ionic info below), and following along with the example code (examples/audio-provider.ts), I encountered a type error:

Error: error TS2345: Argument of type 'AudioTrackOptions' is not assignable to parameter of type 'PlaylistItemOptions'.
  Types of property 'playFromId' are incompatible.
    Type 'string' is not assignable to type 'number'.

I suspect the setPlaylistItems function in the example code should be this:

```
let options: PlaylistItemOptions = {};
```
instead of 

`let options: AudioTrackOptions = {};  `

~~~~~~~~~~~~~
Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.2
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.3.1
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v17.8.0 (/usr/local/bin/node)
   npm    : 8.9.0
   OS     : macOS Monterey

**Comment by phiamo** [comment]
Can you verify and create a pr , please
