### ISSUE TITLE
 java.lang.RuntimeException: Unable to start service org.dwbn.plugins.playlist.service.MediaService

### ISSUE THREAD

**Issue by emilsaj** [phiamo/capacitor-plugin-playlist#24]
Hello. First of all; very excited to find this plugin, as it is essential for us, and we hope to get it working! Thanks a lot for your work!

I've tried to follow the documentation and so far tried to make it work on Android.
Unfortunately, I've bumped into the following error, which causes the app to crash as soon as I try to play Audio. Is it something you have seen before? I'm a bit new to these 'kind' of plugins, so I might have missed something obvious.

![image](https://user-images.githubusercontent.com/100521595/173399623-7faea86c-86e3-424f-9132-6a34450b001a.png)

**Comment by PavelShvets-dev** [comment]
@emilsaj hi! Actually the same issue was there: https://github.com/phiamo/capacitor-plugin-playlist/issues/13

You just need to put all required icons as shown on the screenshot (see issue 13) and the error will disappear.

**Comment by emilsaj** [comment]
@PavelShvets-dev my bad, I somehow missed that one!
Thanks a lot - will try this later.

Btw: 
If I have questions/requests or something that I believe is an issue, so basically anything that could be up for a discussion, how is it prefered that I communicate this? Is it always through issues?

Kinda new in this 'setting' so apologize for any silly questions.

**Comment by phiamo** [comment]
Sure issue would be the place, or you have another idea.. open for anything
😄

emilsaj ***@***.***> schrieb am Di., 14. Juni 2022, 14:23:

**Comment by emilsaj** [comment]
@phiamo I've been playing around with the plugin a bit now, and it seems to do exactly what it's supposed to. Huge props! 💯 

What are the plans for this great plugin in regards to maintenance/further implementation in the future? Are you guys using it actively in projects yourselves or what is your motivation atm? :-) 
I am asking since I want to implement it in my project, but I am not a native Android/iOS dev, so my contributions for maintenance would be limited. 

PS: I've found some small issues, and trying to figure out how much is 'worth' reporting - guess that depends on the answer to the above as well :-)

**Comment by phiamo** [comment]
yes i am actively using it in a project but am neither swift nor android developer and I dont have much time at the moment
For me it works ok at the moment, and every improvement is highly welcome!
