### ISSUE TITLE
Is there any way to hide the skip forward/back buttons from the audio control notification?

### ISSUE THREAD

**Issue by emilsaj** [phiamo/capacitor-plugin-playlist#27]
Right now, even when there are no more items in the queue, the buttons are disabled, but when pressed they still stop the audio and send an RMXSTATUS_COMPLETED event. I also have some situations where I want the buttons disabled, even though I have something in the queue. Is that possible? :-) 

Side not: I expected the RMXSTATUS_COMPLETED event to only be emitted when the current track has been listened to the end (right now it's also when skip is used), as I want the app to behave differently in this case. But that might just be me misinterpreting 'The reported track has completed playback.'

Tested on Android - Huawei P30 Pro

**Comment by phiamo** [comment]
Its possible in the underling library somehow...i remember from 1 or two years ago
But one needs to dig how thats done i  there and find a way to build it in here generically..
I would assume disabling them generally should be opt in

**Comment by emilsaj** [comment]
I made a pull request to fix the disabled next button, so it actually behaves as disabled.
#37
