### ISSUE TITLE
How to add the songs?

### ISSUE THREAD

**Issue by rwwagner90** [phiamo/capacitor-plugin-playlist#3]
I do not see anything in the docs about how to add the songs/playlist.

**Comment by phiamo** [comment]
Indeet the doc is far from good 
Check the example here:
https://github.com/phiamo/capacitor-plugin-playlist/blob/221fda96bafe16fc57086b81fc1d02f435579dd2/examples/audio-provider.ts#L59

**Comment by rwwagner90** [comment]
@phiamo I was able to get everything working. However, `setAudioTracks` is incorrect. It's actually `setPlaylistItems` https://github.com/phiamo/capacitor-plugin-playlist/blob/main/src/RmxAudioPlayer.ts#L197

**Comment by phiamo** [comment]
thanks for the PR!
