### ISSUE TITLE
Pull requests question

### ISSUE THREAD

**Issue by emilsaj** [phiamo/capacitor-plugin-playlist#33]
Hi! 
I made a few pull requests that have not been accepted; please let me know if there is anything I've done wrong, and I'll gladly correct it! :-)

**Comment by phiamo** [comment]
Hi @emilsaj i am super happy to see things goong on here 😊 just didnt find time to look.

**Comment by phiamo** [comment]
@emilsaj thank you so much for bringing this forward!!!
