### ISSUE TITLE
Thanks for the work !

### ISSUE THREAD

**Issue by riderx** [phiamo/capacitor-plugin-playlist#42]
I just added your plugin to [awesome-capacitor](https://github.com/riderx/awesome-capacitor) thanks !

**Comment by phiamo** [comment]
thank you and all the contributors !!!!!!

**Comment by phiamo** [comment]
Of course, thanks a lot! any pr is appreciated

Jakub Niewczas ***@***.***> schrieb am Mi., 10. Aug. 2022,
14:16:
