### ISSUE TITLE
isAtEnd, isAtBeginning, hasPrevious, hasNext are incorrectly reported in rmxstatus_TRACK_CHANGED for first track

### ISSUE THREAD

**Issue by timstoute** [phiamo/capacitor-plugin-playlist#48]
in iOS, for first track of playlist, isAtEnd, isAtBeginning, hasPrevious, and hasNext are incorrectly reported in rmxstatus_TRACK_CHANGED

When player is starting a new playlist, having just "setPlaylistItems", I'm seeing each of these have the opposite of what I expected. 

What I expected:

- isAtEnd: false, 
- isAtBeginning: true, 
- hasPrevious: false, 
- hasNext: true

What I'm observing: 

- isAtEnd: true, 
- isAtBeginning: false, 
- hasPrevious: true, 
- hasNext: false

These values need to be initialised appropriately, but so far I'm unsure of where this would be done, perhaps in func setPlaylistItems

**Comment by phiamo** [comment]
@timstoute thanks for the hint, i just applied a few changes which hopefully fix that

**Comment by timstoute** [comment]
@phiamo thanks for these changes, they helped a lot and served to make event reporting overall more stable and predictable
