### ISSUE TITLE
Ionic 5 + Capacitor - crashes app on register of class

### ISSUE THREAD

**Issue by daveshirman** [phiamo/capacitor-plugin-playlist#5]
What I've done:

- Added the plugin with `npm i ...`
- Synced my Capacitor plugins with `npx cap sync`.
- Added the required `ext { ... }` bits to variables.gradle.
- Tried to register the plugin in `MainActivity.java` as directed.

**With the plugin register line left in, like so:**

```
    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      add(PlaylistPlugin.class);
    }});

```
**I get a crash on load with:**

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ripper.aomtest/com.ripper.aomtest.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to org.dwbn.plugins.playlist.App

**Comment by phiamo** [comment]
You need to add it to the application in AndroidManifest.xml
E.g.

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:name="org.dwbn.plugins.playlist.App"
        android:networkSecurityConfig="@xml/network_security_config"
    >


dave <notifications@github.com> schrieb am Mi., 3. März 2021, 17:52:

**Comment by daveshirman** [comment]
Thanks, that fixed the crash.  Definitely worth adding that to the readme!
Having other issues with AudioProvider class itself, but I'll raise another ticket.
Thank you.

**Comment by phiamo** [comment]
is in readme :/
