### ISSUE TITLE
iOS, RMXSTATUS_LOADED event fires many times for one track

### ISSUE THREAD

**Issue by timstoute** [phiamo/capacitor-plugin-playlist#55]
in iOS, I'm seeing the RMXSTATUS_LOADED event fire many times for one track. 14 instances for example.

In each case the reported values are identical, for example all 14 events show:

`{"currentPosition":0,"status":"paused","isStream":0,"playbackPercent":0,"bufferStart":0,"duration":310.4432373046875,"bufferEnd":310.4432373046875,"bufferPercent":100,"trackId":"b2589af6cb533f74f802234c4bec2508","currentIndex":0}`

Is this expected?

**Comment by timstoute** [comment]
additional observation: 

the apparently abnormal amount of events fired (I'm also seeing an unexpected amount of RMXSTATUS_TRACK_CHANGED events too for the same track) happens on the second or more calls to this.audioPlayer.setPlaylistItems()

So the first time setPlaylistItems() is utilized, the player plays tracks and reports events in a reasonable and expected fashion. BUT, when I pass a second set of play list items to the player via setPlaylistItems() I see this explosion of event logs and degraded app performance.  

The plugin code indicates that setPlaylistItems() should remove and replace all existing tracks and return the player to a state where a new playlist can be played.

**Comment by emilsaj** [comment]
Is this with or without @phiamo's change in commit #218047098a4ec089899a3d1db60fd075c60a54c9 'improve track change handling'?

**Comment by timstoute** [comment]
yes, I believe so; (unless I'm missing something):

I have run _npm update_ in my project folder; I have also run _ionic build, npx cap sync, and npx cap open ios_.

Additionally I have verified that my local project's node_module files:

- project/node_modules/capacitor-plugin-playlist/ios/Plugin/RmxAudioPlayer.swift
-  project/node_modules/capacitor-plugin-playlist/ios/Plugin/AVBidirectionalQueuePlayer.swift

include the changes for that commit: [https://github.com/phiamo/capacitor-plugin-playlist/commit/218047098a4ec089899a3d1db60fd075c60a54c9](https://github.com/phiamo/capacitor-plugin-playlist/commit/218047098a4ec089899a3d1db60fd075c60a54c9)

**Comment by timstoute** [comment]
In RmxAudioPlayer.swift, in the func addTrackObservers(_ playerItem: AudioTrack?), the following observers are added for each track:

- status
- duration
- loadedTimeRanges
- selector: #selector(playerItemDidReachEnd(_:))
- selector: #selector(itemStalledPlaying(_:))

But, in avQueuePlayer.removeTrackObservers(playerItem), only the following observers are removed for a track:

- name: .AVPlayerItemDidPlayToEndTime
- name: .AVPlayerItemPlaybackStalled

Could the extraneous events being reported be because the track observers are not being completely removed for each track as part of the  setPlaylistItems() call stack? For example, it seems that the "status", "duration" and "loadedTimeRanges" observers are never removed for any track.

**Comment by phiamo** [comment]
Imho you are right, should be the case .. i am without big coding util atm,
can you create a pr?

Tim Stoute ***@***.***> schrieb am Sa., 6. Aug. 2022, 15:02:

**Comment by timstoute** [comment]
@phiamo - I'm pretty new to Swift and running into issues with the removal of the track observers to test the theory.  I'm comparing the plugin code with https://developer.apple.com/documentation/avfoundation/media_playback/observing_playback_state.  I'll continue, but whenever you have an opportunity would appreciate your further insights.

**Comment by timstoute** [comment]
@phiamo - having spent more time investigating, I'm thinking the theory that track removers need to be removed is incorrect. I suspect the issues I'm having are stemming from something else, and possibly the way in which I am calling setPlaylistItems().

**Comment by emilsaj** [comment]
@timstoute what way were you doing it that was not correct, and how did you fix it? :-)

**Comment by timstoute** [comment]
@phiamo - I'm still investigating, and I'll let you know what I find. But in the mean time didn't want you want you spending any cycles on an issue that might be unrelated to plugin code.

**Comment by timstoute** [comment]
@phiamo - I was accidentally subscribing to status events more than once for the player instance and so was seeing multiples of status messages 
thanks again for your work on this project

**Comment by timstoute** [comment]
see above
