### ISSUE TITLE
STATUS_SKIP_FORWARD event is not being reported in iOS

### ISSUE THREAD

**Issue by timstoute** [phiamo/capacitor-plugin-playlist#56]
My tests in iOS are finding that the STATUS_SKIP_FORWARD status event is not being fired when playNext function is called in RmxAudioPlayer.swift (approx. line 316)

It appears that the bool var _isCommand_ is false even though true is passed to the playNext function. When isCommand is false, the line:

onStatus(.rmx_STATUS_SKIP_FORWARD, trackId: playerItem?.trackId, param: param)

will not be called.

**Comment by phiamo** [comment]
hmm are you calling the playNext from your code or triggering it from the control center?
i am at the moment unsure if the isCommand if case is needed at all

**Comment by timstoute** [comment]
I am calling playNext from code. I see that when playNext is called from the control center the STATUS_SKIP_FORWARD  event is reported.  It seems to me that the isCommand if case is not needed.

**Comment by ronildo** [comment]
This line here is the issue:

https://github.com/phiamo/capacitor-plugin-playlist/blob/main/src/web.ts#L197

The status should be this: RMX_STATUS_SKIP_FORWARD instead of RMX_STATUS_SKIP_BACK

**Comment by phiamo** [comment]
@timstoute did you ever digged deeper there?
