### ISSUE TITLE
Player skip buttons

### ISSUE THREAD

**Issue by ronildo** [phiamo/capacitor-plugin-playlist#57]
This is just a question, not an issue.
Is there a way to add the skip buttons like in the print screen below?

![AE40EEF9-40BF-4629-8273-777DFD3633D1](https://user-images.githubusercontent.com/622159/186954215-61abd94e-db1c-4f49-9f0e-b1766366a5e3.jpeg)

thanks for the awesome work, this plugin will fit like a glove for me.

**Comment by timstoute** [comment]
In my experience you would need to use the RmxAudioPlayer seek function, and do some maths with the available values from status events such as playbackPercent which is included in the RMXSTATUS_PLAYBACK_POSITION  status event, and duration which is included in the RMXSTATUS_DURATION status event.

**Comment by ronildo** [comment]
Thanks for replying Tim, I’ll see if I can find any information on how to add the buttons, thank you!

**Comment by PavelShvets-dev** [comment]
@ronildo hi! That would be a great refinement and it seems to be not too hard. For iOS we need to add new optional commands here

RmxAudioPlayer.swift: initializeMPCommandCenter

seekBackwardCommand
seekForwardComand

https://developer.apple.com/documentation/mediaplayer/mpremotecommandcenter

And then we need to register new events outside.

Android version looks harder for me…🙂 

Anyway, I will be glad to help the development of this function

**Comment by ronildo** [comment]
Hi @PavelShvets-dev thanks for the reply, I wish I could help, I only know JavaScript (yet). I wish I could help.

thanks for the links, I will see if I can implement this on my app.

**Comment by mariusbolik** [comment]
Yes, this would be a helpful feature! 
[capacitor-music-controls-plugin-new](https://github.com/gokadzev/capacitor-music-controls-plugin-new) already has this type of functionality. Maybe this could be helpful.

**Comment by phiamo** [comment]
any MR welcome :D
