### ISSUE TITLE
iOS: Playback of audio on other apps stop when I enter my app that has this plugin installed

### ISSUE THREAD

**Issue by trabdin** [phiamo/capacitor-plugin-playlist#63]
Hi,

I tried this plugin in my Ionic app on iOS, and I noticed that when I have something else playing in another app (for example YouTube Music) and I enter my app with the playlist plugin installed (before even using the plugin in any way or playing any audio), playback of the audio in the other app stops automatically...

Has anyone else noticed something like this or am I perhaps missing something?

Thanks!

**Comment by ronildo** [comment]
I haven't noticed in the app I'm building, but in general that happens with lots of other apps too... for example, gmail stops the audio, sometimes twitter also.

**Comment by ghenry22** [comment]
You need to adjust your audio session type on iOS.  Can’t remember the exact code but you can set your audio session to be exclusive, to mix with others etc which will change this behaviour.
