### ISSUE TITLE
Example AudioProvider class has build issues

### ISSUE THREAD

**Issue by daveshirman** [phiamo/capacitor-plugin-playlist#7]
- L8: AudioTrackOptions no exported member
- L12: Cannot find module environment (not a biggie, I just commented out and set L40 to true).
- L53, 55, 65 - viewedUntil does not exist on AudioTrack

To get round this, I have set the relevant method signatures to take either `audioTrack: any` or `currentItem?: any`

**Comment by ShaunBrassell** [comment]
Same here, thwarted before I could even begin!

**Comment by phiamo** [comment]
added the missing interface :/
