### ISSUE TITLE
[chore] Update Exomedia to 5.0.0 and playlistCore to latest

### ISSUE THREAD

**Issue by ghenry22** [phiamo/capacitor-plugin-playlist#82]
Exomedia 5.0.0 removes the requirement for legacy android support libraries and updates deps.

PlaylistCore latest removes the same and adds some features like Android Media Controls position scrubber.  If there is no new release for PlaylistCore then publish a fork so it can be updated and included.

Can then update the plugin to remove jetifier for android builds.

Will need to test all functions for any breaking changes.

**Comment by phiamo** [comment]
done in 0.6
