### ISSUE TITLE
Request to upgrade to Capacitor 5 version.

### ISSUE THREAD

**Issue by parkmoonsu** [phiamo/capacitor-plugin-playlist#83]
Playstore required sdk 33 version, so build to that plug-in is no longer possible.

When adding npm capacitor-plugin-playlist@latest, the build is not possible due to peer dependency.

I beg you.

**Comment by phiamo** [comment]
@parkmoonsu could you provide a MR please ?

**Comment by phiamo** [comment]
done in 0.5
