### ISSUE TITLE
When to use this instead of native-audio?

### ISSUE THREAD

**Issue by mustafa0x** [phiamo/capacitor-plugin-playlist#87]
Hi, thanks for this impressive work! I'm a little new to the world of capacitor. When should I pick this over https://github.com/capacitor-community/native-audio?

Thanks!

**Comment by phiamo** [comment]
Hi, thanks for sharing this didn't know it yet. It looks like this one does
a similar job.
Our focus here was on having seamlessly playing a whole playlist natively
and not just one file. I am unsure if the plugin you mentioned supports
this as well.

Our use case is a audio App which can run for hours in the background
providing audio from various files

mustafa0x ***@***.***> schrieb am Mi., 8. Mai 2024, 14:25:

**Comment by mustafa0x** [comment]
I see, thanks @phiamo!
