### ISSUE TITLE
setPlaylistItems Not Working on iOS

### ISSUE THREAD

**Issue by Yehya22** [phiamo/capacitor-plugin-playlist#90]
Hi there,

I've encountered an issue where the `setPlaylistItems` method works perfectly on web and Android but doesn't seem to function on iOS.
 
I've created a test repository to demonstrate the problem: [https://github.com/Yehya22/cap-playlist-plugin-example](https://github.com/Yehya22/cap-playlist-plugin-example)

Could someone please help me understand why this might be happening on iOS and how I can fix it? Any guidance would be greatly appreciated!

Thank you!

**Comment by phiamo** [comment]
what was the problem?

**Comment by Yehya22** [comment]
Hi, sorry for the late reply.
I was setting trackId as an integer, it should be a string, and there was another problem related to svelte 5 runes.

**Comment by Yehya22** [comment]
For anyone who uses Svelte 5 Runes and has the same issue with setPlaylistItems not working in iOS, please make sure to use 
`setPlaylistItems($state.snapshot())`
