### ISSUE TITLE
[ios] albumArt/MPMediaItemPropertyArtwork: only shows in dev, not in prod

### ISSUE THREAD

**Issue by mustafa0x** [phiamo/capacitor-plugin-playlist#96]
The albumArt shows fine on ios devices in dev mode. I've tested on the simulator and a physical device. However, the app store app only shows the default image. Even though the code is the exact same.

(In the sample image below, the album art is the "Brain ..." image)

![image](https://github.com/user-attachments/assets/a9d3c8ce-c446-4c5b-b256-c90d4cd1b856)

**Comment by mustafa0x** [comment]
Strangely, tweaking url fixed this.

**Comment by phiamo** [comment]
What kind of tweak did you use, maybe you can create a MR for the readme to document this ?

**Comment by mustafa0x** [comment]
I was using `albumArt: location.origin + /image.png`. That doesn't work in prod since `location.origin == 'capacitor://localhost'`.
